### ISSUE TITLE
Questions for the paper

### ISSUE THREAD

**Issue by LebronX** [95616ARG/PRDNN#3]
Hi,

I have two questions when reading your paper.

1. question about the non-linearity in section 3.1 of the paper. Why do you say "coupling cause the repair computationally infeasible"? Although changing the weight will make the change of output become non-linear, from the perspective of **computing**, why this make it not computable?

2. If I understand correctly, after computing a repaired DDNN, you don't transfer it back to normal DNN, right?

Thanks!

**Comment by matthewsot** [comment]
Thanks for the interest in our work!

> question about the non-linearity in section 3.1 of the paper. Why do you say
> "coupling cause the repair computationally infeasible"? Although changing the
> weight will make the change of output become non-linear, from the perspective
> of computing, why this make it not computable?

To clarify, by "computationally infeasible" here, we meant just "impractical."
As you point out, it would be computable, but it would become NP-hard and in
practice much slower. See this paper for a description of how one might do this
using a modern solver:
https://easychair-www.easychair.org/publications/download/CWhF

Our construction reduces it to an LP problem that can be solved in polynomial
time.

> If I understand correctly, after computing a repaired DDNN, you don't
> transfer it back to normal DNN, right?

Correct.

Please let us know if you have any other questions!

**Comment by LebronX** [comment]
Hi,

Thanks for the reply! The paper you referred uses SMT-solver as backend. But in my understanding, it can also be reduced to a LP problem and use LP solver to solve it, no?

Thanks!

**Comment by matthewsot** [comment]
Hello,

In that paper, they do **not** use DDNNs, they instead directly find a repair for the DNN and produce a DNN as the result. This is an NP-hard problem and there is no obvious way to reduce it to an LP or use an LP solver to solve it. So, their approach cannot use an LP solver to solve it (the reason is as noted in your original quote --- because of the "coupling", it's an inherently non-linear problem so you can't use a linear programming solver).

Basically what our paper points out is that if you try to repair a DDNN (instead of a DNN) then you can in fact reduce it to an LP problem. But that's specifically due to the use of DDNNs --- for DNNs you need a full SMT solver.

The one exception to this is when patching the very last layer. In that case, both the DNN (that paper) and DDNN (our paper) repair algorithms produce exactly the same result so both can use an LP solver. But that's only for the very final layer --- for all other layers, our approach can be reduced to LP while the other requires an SMT solver (to reason about the non-linearities).

Hope that helps clarify things!

**Comment by LebronX** [comment]
Aha I understand now! Thanks a lot for the explanation!
